### ISSUE TITLE
unable to select some comparison metrics: Failed to deserialize request

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1337] opened 2022-05-25 11:04 UTC
Unable to select few comparison metrics, for example, `context-switches` with error:
```
Failed to deserialize request: Error("unknown variant `context-switches`, expected one of `instructions:u`, `cycles:u`, `faults`, `max-rss`, `task-clock`, `wall-time`, `cpu-clock`", line: 1, column: 126)
```

* Open some compare link, for example https://perf.rust-lang.org/compare.html?start=f80e454450c891c075617d23532c6eb317f4471d&end=6ac8adad1f7d733b5b97d1df4e7f96e73a46db42&stat=instructions:u
* Click `Do another comparison` and select other comparison metric,  `context-switches`, for example.
* Click submit, error will appear, but expected instead to show page with that metric.

This worked recently, so broken in last few commits, i guess.

**Comment by klensy** [comment] 2022-05-25 11:07
maybe #1322 ?

**Comment by Kobzol** [comment] 2022-05-25 11:15
Yeah this was most probably caused by my PR, I haven't seen this metric before. I'll fix it today.

**Comment by klensy** [comment] 2022-05-25 11:16
Not only this, one, some others too, so, please check other ones.

**Comment by Kobzol** [comment] 2023-06-04 07:44
Closing for now, let me know if there are any other metrics missing.

**Closed by Kobzol** 2023-06-04 07:44 UTC
