### ISSUE TITLE
Measure binary size

### ISSUE THREAD

**Issue by anp** [rust-lang/rustc-perf#643] opened 2020-04-05 17:28 UTC
It would be very useful to be able to assess the size of the created artifacts over time. Ideally including information like section sizes, etc.

**Comment by Mark-Simulacrum** [comment] 2020-05-11 22:06
Going to go ahead and close this as a duplicate of the (much) earlier https://github.com/rust-lang/rustc-perf/issues/145 :)

**Closed by Mark-Simulacrum** 2020-05-11 22:06 UTC
